(() => {
  'use strict';
  const KEY = 'denshaTimerSettings.v4';
  const DEF = { defaultSegments: 3, railColorMode: 'single', reducedMotion: true, wakeLock: true, vibration: true, sound: true };
  const NS = 'http://www.w3.org/2000/svg';
  const C = 130, R = 98, SR = 119;
  const MULTI = [['#38bdf8', '#0284c7'], ['#a78bfa', '#7c3aed'], ['#fbbf24', '#d97706'], ['#34d399', '#059669'], ['#fb7185', '#e11d48']];
  const SINGLE = ['#38bdf8', '#0284c7'];
  const s = { total: 600, segments: 3, elapsed: 0, running: false, started: 0, before: 0 };
  let cfg = { ...DEF };
  let raf = 0;
  const $ = (id) => document.getElementById(id);
  const e = {
    card: $('timerCard'), rail: $('railLayer'), seg: $('segmentLayer'), st: $('stationLayer'), tr: $('trainLayer'),
    time: $('timeText'), label: $('stateText'), summary: $('segmentSummary'), current: $('currentSegment'), left: $('segmentLeft'), percent: $('progressPercent'), badge: $('visualStatusBadge'),
    min: $('minutesInput'), parts: $('segmentsInput'), main: $('startPauseButton'), reset: $('resetButton'), live: $('screenReaderStatus'),
    toggle: $('settingsToggle'), close: $('settingsCloseButton'), panel: $('settingsPanel'), back: $('sheetBackdrop'), save: $('saveSettingsButton'),
    defParts: $('defaultSegmentsInput'), colorMode: $('railColorModeInput'), wake: $('wakeLockInput'), vib: $('vibrationInput'), sound: $('soundInput'), motion: $('reducedMotionInput')
  };
  const clamp = (v, min, max) => Math.min(Math.max(v, min), max);
  const text = (node, value) => { if (node) node.textContent = value; };
  const fmt = (sec) => { const x = Math.max(0, Math.ceil(sec)); return `${Math.floor(x / 60)}:${String(x % 60).padStart(2, '0')}`; };
  const make = (name, attrs = {}) => { const n = document.createElementNS(NS, name); Object.entries(attrs).forEach(([k, v]) => n.setAttribute(k, String(v))); return n; };
  const clear = (node) => { while (node.firstChild) node.removeChild(node.firstChild); };
  const point = (r, deg) => { const a = (deg - 90) * Math.PI / 180; return { x: C + r * Math.cos(a), y: C + r * Math.sin(a) }; };
  const arc = (r, a, b) => { const p = point(r, a), q = point(r, b), big = Math.abs(b - a) > 180 ? 1 : 0; return `M ${p.x.toFixed(2)} ${p.y.toFixed(2)} A ${r} ${r} 0 ${big} 1 ${q.x.toFixed(2)} ${q.y.toFixed(2)}`; };
  const pair = (i) => cfg.railColorMode === 'multi' ? MULTI[i % MULTI.length] : SINGLE;
  function load() { try { cfg = { ...DEF, ...(JSON.parse(localStorage.getItem(KEY) || 'null') || {}) }; } catch { cfg = { ...DEF }; } cfg.defaultSegments = clamp(Math.round(Number(cfg.defaultSegments) || 3), 1, 12); cfg.railColorMode = cfg.railColorMode === 'multi' ? 'multi' : 'single'; }
  function save() { localStorage.setItem(KEY, JSON.stringify(cfg)); }
  function apply() { document.body.classList.toggle('reduced-motion', !!cfg.reducedMotion); e.defParts.value = cfg.defaultSegments; e.colorMode.value = cfg.railColorMode; e.wake.checked = !!cfg.wakeLock; e.vib.checked = !!cfg.vibration; e.sound.checked = !!cfg.sound; e.motion.checked = !!cfg.reducedMotion; }
  function sync() { s.total = Math.round(clamp(Number(e.min.value) || 10, 0.5, 600) * 60); s.segments = clamp(Math.round(Number(e.parts.value) || cfg.defaultSegments), 1, 12); if (!s.running) s.elapsed = clamp(s.elapsed, 0, s.total); }
  function renderBase() { clear(e.rail); e.rail.appendChild(make('circle', { class: 'rail-base', cx: C, cy: C, r: R })); e.rail.appendChild(make('circle', { class: 'rail-line', cx: C, cy: C, r: R - 10 })); e.rail.appendChild(make('circle', { class: 'rail-line', cx: C, cy: C, r: R + 10 })); for (let i = 0; i < 36; i++) { const a = i * 10, p = point(R - 13, a), q = point(R + 13, a); e.rail.appendChild(make('line', { class: 'sleeper', x1: p.x, y1: p.y, x2: q.x, y2: q.y })); } }
  function renderSegments(pct) { clear(e.seg); const slice = 360 / s.segments, gap = Math.min(3.2, slice * 0.18), done = Math.floor(pct * s.segments), active = Math.min(s.segments - 1, Math.floor(pct * s.segments)); for (let i = 0; i < s.segments; i++) { const [base, strong] = pair(i); let cls = 'segment-arc guide'; if (i < done || pct >= 1) cls = 'segment-arc done'; if (s.running && i === active) cls = 'segment-arc active'; e.seg.appendChild(make('path', { class: cls, d: arc(R, i * slice + gap / 2, (i + 1) * slice - gap / 2), 'stroke-width': 18, style: `--segment-color:${base};--segment-strong-color:${strong}` })); } renderCaps(pct); }
  function renderCaps(pct) { const done = Math.floor(pct * s.segments), next = Math.min(s.segments, Math.max(1, Math.ceil(pct * s.segments))); for (let i = 0; i < s.segments; i++) { const a = i * (360 / s.segments), p = point(R, a), q1 = point(R - 16, a), q2 = point(R + 16, a), [base, strong] = pair(Math.max(0, i - 1)); e.seg.appendChild(make('line', { class: 'split-cut', x1: q1.x, y1: q1.y, x2: q2.x, y2: q2.y })); const g = make('g', { class: `${i <= done ? 'split-cap-passed' : ''} ${i === next ? 'split-cap-next' : ''}` }); g.appendChild(make('circle', { class: 'split-cap-outer', cx: p.x, cy: p.y, r: 7.6 })); g.appendChild(make('circle', { class: 'split-cap-inner', cx: p.x, cy: p.y, r: 4.2, style: `--segment-color:${base};--segment-strong-color:${strong}` })); e.seg.appendChild(g); } }
  function renderStations(pct) { clear(e.st); const done = Math.floor(pct * s.segments), next = Math.min(s.segments, Math.ceil(pct * s.segments)); for (let i = 0; i <= s.segments; i++) { const p = point(SR, i === s.segments ? 360 : i * (360 / s.segments)), [base, strong] = pair(i === 0 ? 0 : i - 1), g = make('g', { transform: `translate(${p.x.toFixed(2)} ${p.y.toFixed(2)})` }); let cls = 'station-dot future'; if (pct >= 1 || i <= done) cls = 'station-dot passed'; if (i === 0) cls = 'station-dot start'; if (i === s.segments) cls += ' goal'; if (pct < 1 && i === Math.max(1, next)) cls = 'station-dot next'; g.appendChild(make('rect', { class: 'station-platform', x: -15, y: -9, width: 30, height: 18, rx: 8 })); g.appendChild(make('circle', { class: cls, cx: 0, cy: 0, r: cls.includes('next') ? 10 : 8.5, style: `--segment-color:${base};--segment-strong-color:${strong}` })); if (cls.includes('next')) g.appendChild(make('circle', { class: 'station-ring', cx: 0, cy: 0, r: 17 })); if (i === s.segments) { const flag = make('text', { class: 'goal-flag', x: 0, y: -23 }); flag.textContent = '🏁'; g.appendChild(flag); } e.st.appendChild(g); } }
  function renderTrain(pct) { clear(e.tr); const p = point(R, pct * 360); e.tr.appendChild(make('circle', { class: 'train-halo', cx: p.x, cy: p.y, r: 18 })); const train = make('text', { class: 'train-icon', x: p.x, y: p.y + 1 }); train.textContent = '🚃'; e.tr.appendChild(train); }
  function render() { sync(); const pct = clamp(s.elapsed / s.total, 0, 1), segSec = s.total / s.segments, segLeft = pct >= 1 ? 0 : segSec - (s.elapsed % segSec), current = Math.min(s.segments, Math.max(1, Math.floor(pct * s.segments) + 1)); renderBase(); renderSegments(pct); renderStations(pct); renderTrain(pct); text(e.time, fmt(s.total - s.elapsed)); text(e.label, s.running ? 'しゅっぱつ中' : pct >= 1 ? 'ゴール！' : s.elapsed > 0 ? 'とまっています' : 'しゅっぱつ まえ'); text(e.summary, `${Math.round(s.total / 60)}分・${s.segments}分割：1駅 ${fmt(segSec)}`); text(e.current, pct >= 1 ? `${s.segments} / ${s.segments}` : `${current} / ${s.segments}`); text(e.left, fmt(segLeft)); text(e.percent, `${Math.round(pct * 100)}%`); text(e.badge, pct >= 1 ? '🏁' : s.running ? '🚃' : '🚉'); text(e.main, s.running ? 'とまる' : s.elapsed > 0 && pct < 1 ? 'またすすむ' : 'しゅっぱつ'); e.card.classList.toggle('is-running', s.running); e.card.classList.toggle('is-finished', pct >= 1); }
  function tick() { if (!s.running) return; s.elapsed = clamp(s.before + (performance.now() - s.started) / 1000, 0, s.total); if (s.elapsed >= s.total) { s.running = false; text(e.live, 'ゴールにつきました。'); } render(); if (s.running) raf = requestAnimationFrame(tick); }
  function reset(announce = true) { s.running = false; s.elapsed = 0; s.before = 0; cancelAnimationFrame(raf); if (announce) text(e.live, 'はじめにもどりました。'); render(); }
  function chooseChips() { document.querySelectorAll('[data-minutes]').forEach((b) => b.classList.toggle('is-selected', Number(b.dataset.minutes) === Number(e.min.value))); document.querySelectorAll('[data-segments]').forEach((b) => b.classList.toggle('is-selected', Number(b.dataset.segments) === Number(e.parts.value))); }
  function startPause() { if (s.running) { s.running = false; s.before = s.elapsed; cancelAnimationFrame(raf); text(e.live, 'でんしゃがとまりました。'); render(); return; } if (s.elapsed >= s.total) reset(false); sync(); s.running = true; s.started = performance.now(); s.before = s.elapsed; text(e.live, 'でんしゃがしゅっぱつしました。'); raf = requestAnimationFrame(tick); render(); }
  function openSheet() { e.panel.hidden = false; e.back.hidden = false; document.body.classList.add('sheet-open'); e.toggle.setAttribute('aria-expanded', 'true'); }
  function closeSheet() { e.panel.hidden = true; e.back.hidden = true; document.body.classList.remove('sheet-open'); e.toggle.setAttribute('aria-expanded', 'false'); }
  function bind() { e.min.addEventListener('blur', () => { e.min.value = String(clamp(Number(e.min.value) || 10, 0.5, 600)); reset(false); chooseChips(); }); e.parts.addEventListener('blur', () => { e.parts.value = String(clamp(Math.round(Number(e.parts.value) || cfg.defaultSegments), 1, 12)); reset(false); chooseChips(); }); document.querySelectorAll('[data-minutes]').forEach((b) => b.addEventListener('click', () => { e.min.value = b.dataset.minutes; reset(false); chooseChips(); })); document.querySelectorAll('[data-segments]').forEach((b) => b.addEventListener('click', () => { e.parts.value = b.dataset.segments; reset(false); chooseChips(); })); e.main.addEventListener('click', startPause); e.reset.addEventListener('click', () => reset(true)); e.toggle.addEventListener('click', openSheet); e.close.addEventListener('click', closeSheet); e.back.addEventListener('click', closeSheet); e.colorMode.addEventListener('change', () => { cfg.railColorMode = e.colorMode.value === 'multi' ? 'multi' : 'single'; render(); }); e.motion.addEventListener('change', () => { cfg.reducedMotion = e.motion.checked; document.body.classList.toggle('reduced-motion', cfg.reducedMotion); }); e.save.addEventListener('click', () => { cfg.defaultSegments = clamp(Math.round(Number(e.defParts.value) || 3), 1, 12); cfg.railColorMode = e.colorMode.value === 'multi' ? 'multi' : 'single'; cfg.reducedMotion = e.motion.checked; cfg.wakeLock = e.wake.checked; cfg.vibration = e.vib.checked; cfg.sound = e.sound.checked; save(); apply(); closeSheet(); render(); }); }
  function init() { load(); apply(); e.parts.value = String(cfg.defaultSegments); bind(); chooseChips(); render(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(() => {}); }
  init();
})();
